### ISSUE TITLE
Incompatibility with OSX < 10.10

### ISSUE THREAD

**Issue by samcarter8** [texstudio-org/texstudio#134]
On the download page https://www.texstudio.org/ it is claimed that texstudio would be compatible with mac OSX 10.8+

However trying to open the version 2.12.8 (both the .dmg version to download and the one installed via homebrew) gives the following error message

```
You can't use this version of TeXstudio with this version of macOS. You have macOS 10.9.5. Qt requires macOS 10.10.0 or later.
Abort trap: 6
```

**Comment by sunderme** [comment]
this is a qt issue (see http://doc.qt.io/qt-5/supported-platforms.html)
homebrew provides qt5.10 ...

**Comment by samcarter8** [comment]
@sunderme qt5 is not compatible with osx 10.9 :( 

If it TXS is really no longer compatible with osx 10.9 maybe it would be good to 
- change the system requirement statement on the download page
- provide an link to 2.12.6 as last version compatible for legacy systems

**Comment by samcarter8** [comment]
Compiling against an older qt version is no longer possible since a couple of versions of TXS, when you started using a few new qt only features. As far as I remember the problem had been a test for the version of osx (which was easy to fix) and a second problem which I don't remember any more. 

I'll just stick with 2.12.6 for now and will be really envious if you keep on developing cool features :)

**Comment by sunderme** [comment]
txs compiles fine against Qt 5.2 and Qt 4.8.

**Comment by samcarter8** [comment]
Trying to compile with qt 4.8.6 I get the following error:

```
src/buildmanager.cpp:360:45: error: no member named 'MV_10_10' in 'QSysInfo'
        if (QSysInfo::MacintoshVersion > QSysInfo::MV_10_10) {
                                         ~~~~~~~~~~^

```

**Comment by sunderme** [comment]
you need to change MV_10_10 to your system values.

**Comment by samcarter8** [comment]
@sunderme This works! You are my TeXStudio hero!

![vg9lt](https://user-images.githubusercontent.com/8226363/39711135-1a57833c-521f-11e8-86db-b8471e3f37a5.png)
