### ISSUE TITLE
problem Compiling or installing in ubuntu 18.04

### ISSUE THREAD

**Issue by vahidajalluian** [texstudio-org/texstudio#129]
### Environment
- TeXstudio: VERSION 2.12.8	
- Qt: 5
- OS: Linux (ubuntu 18.04) 
- TeX distribution:  texlive

I was going to compile texstudio on my laptop but it seems that there is a problem. 
`/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libpoppler-qt5.so: undefined reference to `qt_version_tag@Qt_5.9'
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libpoppler-qt5.so: undefined reference to `QDateTime::QDateTime(QDateTime&&)@Qt_5'
`
How can I solve it?

**Comment by sunderme** [comment]
works fine here.

make clean   missing ?

**Comment by vahidajalluian** [comment]
The problem of installing solved via recompiling libpoppller in ubuntu 18.04. but still it does not run. whether using .deb of ubuntu 17.10 or using your repository or installing from source.
Where is the problem? how can I make a report for solving this issue?

**Comment by sunderme** [comment]
if you compile poppler on your system on your own, the scope is way beyond what we want to provide support for ...
the ppa (see texstudio.org) provides current and bleeding edge packages.

**Comment by vahidajalluian** [comment]
I said I used all of them the one in the ppa, the in github and the one in
website, non of them worked on ubuntu 18.04

**Comment by sunderme** [comment]
libpoppler is not provided by us. It sounds like you compiled that on your own and we are not debugging that.
I upgraded to ubuntu 18.04 two hours ago and managed to get txs compiled and running, so there seems not to be a fundamental problem with ubuntu's poppler.

**Comment by vahidajalluian** [comment]
here this is the log i can provide

[_usr_bin_texstudio.1000.crash.txt](https://github.com/texstudio-org/texstudio/files/2012489/_usr_bin_texstudio.1000.crash.txt)

**Comment by sunderme** [comment]
this is a crash report and not even a backtrace. No idea what I should do with it, especially since it has nothing do a compile problem ?

**Comment by vahidajalluian** [comment]
How can I report you a backtrace?

**Comment by vahidajalluian** [comment]
This one solved my problem too 
https://github.com/texstudio-org/texstudio/issues/162
