### ISSUE TITLE
Autocomplete keyvalues from external glossaries file broken

### ISSUE THREAD

**Issue by Nerithi** [texstudio-org/texstudio#4370]
I did a search yesterday to see if there was a similar issue already, but haven’t been able to find something. If there is, my apologies, and please point me to the solution.

### Environment

- TeXstudio: 4.9.2
- Qt: 6.10.1
- OS: Windows 11
- TeX distribution: TeX Live 2026

### Expected behavior

When loading an external glossary file from a different directory via `\loadglsentries{path/to/file}`, Texstudio will offer the defined keyvalues as a list to autocomplete when typing a glossaries command such as `\gls{entry}` or `\ac{differententry}`.

### Actual behavior

I have two versions of Texstudio on my computer, 9.2.1 as a proper install and 4.8.8 as a portable installation with Qt 6.9.1. The glossary file I load is in a directory above my project, since I use the same glossary for several projects at the same time, so the structure looks something like this:

```
parent-directory/glossary/glossary-file.tex
parent-directory/project-directory/project-root-document.tex
parent-directory/project-directory/project-included-file.tex
```

Most of the time, I use glossary entries in the included file(s), but there are also some uses in the root document.

`glossaries.cwl` and `glossaries-extra.cwl` are both enabled. `project-root-document.tex` is explicitly declared as the root document in Texstudio.

With the portable 4.8.8 install, everything works fine. Once I start typing a glossaries command, `\ac{}` or `\gls{}`, I get the autocompletion list. In 4.9.2, I get `\gls{gls-label}` instead, and there is no list of glossary entries/acronyms to autocomplete from.

Consulting the documentation, specifically https://texstudio-org.github.io/background.html#loaded-documents, I tried to disable, when it didn’t work, re-enable loading included files, caching documents, as well as adding `% !TeX root = root-filename` to the included files, as well as closing and starting up both Texstudio and the computer after each change.

I also tried disabling and re-enabling glossaries.cwl and glossaries-extra.cwl. Nothing works.

I also checked on my work computer, where MiKTeX 24 and Texstudio 4.8.7 are installed (I know they are out of date. IT updates both when they feel like it, which is usually every 2-3 years or so).

**Note:** When compiling project-root-document, all of the glossary terms appear in the output as intended, regardless of whether the Texstudio version is 4.9.2, 4.8.8 or 4.8.7. It’s *not* an issue of the glossary-file not being found by Tex Live. There are no compilation errors whatsoever.

### How to reproduce

I’m not sure how to reproduce this issue, since it works fine both with 4.8.8 as a portable install on the same computer, using the same Texlive distribution, and on a different computer with an even older version of Texstudio and MiKTeX. I vaguely remember having this issue with 4.9 already, but I equally vaguely recall that I could fix it by redeclaring the project-root-document as root and opening glossary-file in alongside the root document. Neither of these solutions work with 4.9.2.

Considering everything works as expected with 4.8.8, I don’t think it’s an issue with the TeX Live install, but I can’t be 100% certain of course. If you need more information, please tell me what.

**Comment by sunderme** [comment]
please attach a minimal example.

**Comment by Nerithi** [comment]
I can’t upload .tex files, so I had to put them as plain code.

```
project-root-document.tex

\documentclass{memoir}

\usepackage[shortcuts]{glossaries}

\loadglsentries{parent-directory/glossary/glossary-file} % full absolute path to parent-directory

\makeglossaries


\begin{document}

When acquiring \ac{ac}, the \acp{term} of use need to be followed to the letter.


\input{project-included-file}


\end{document}

```

```
project-included-file.tex

\Glspl{term} for the usage of \acl{ac} tend to be quite specific.

```

```
glossary-file.tex

\newglossaryentry{term}{name={term}, description={definition}}

\newacronym{ac}{AC}{air conditioning}

```

**Comment by sunderme** [comment]
okay, the issue is that txs does no longer offer all glossary-entries in the main completer.
Now it works in 2 steps:
1) complete the commad, e.g. `\gls{|}` 
2) now with the cursor in the gls argument, open the completer with ctrl+space.
    Now it offers gloaary entries only.

<img width="642" height="328" alt="Image" src="https://github.com/user-attachments/assets/183140aa-728f-46e9-bcb5-d588e5d615c0" />

**Comment by merlingoescrazy** [comment]
I had the same issue as @Nerithi yesterday.

I am sure that this used to be different when I was working on my Thesis.
Has this feature been removed? Or is this a bug that will be fixed in the future?

**Comment by sunderme** [comment]
it is just a different way of handling glossary. Main point is that they are now separate from labels.

**Comment by Nerithi** [comment]
@sunderme I see, thank you for explaining. I can see the logic in having the two separate, not least because it means that one doesn’t have all of the glossary entries to scroll through in the main completer. It does, however, also require two more keystrokes to get to the actual labels, which isn’t terribly great if you use glossaries a lot, for example in a thesis or a monograph. For me, it means that I’ll have anything between 50 and 200 keystrokes more per page when writing. That adds up to a lot when you regularly write texts of 150 pages and more.

Would there be a possibility to include autocompletion back in when typing the first letter of the label IN the brackets? So `\gls{a}` and the completer offers “ac, a-nother-label, a-third-label” and so on, without having to press ctrl + space?

Otherwise I think I’ll revert back to 4.8.8, where it still works the old way. I tried it yesterday and it just takes so much longer to type now, plus it keeps throwing me out of the writing flow.

**Comment by sunderme** [comment]
implemented that completer is opened when a letter is typed innto a glossary argument.

**Comment by Nerithi** [comment]
Lovely, thank you!
