### ISSUE TITLE
compile error with Qt5.15rc

### ISSUE THREAD

**Issue by sunderme** [texstudio-org/texstudio#1083]
txs master does not compile with Qt5.15 rc

Not sure if its qt5.15's or txs' fault ...

### Environment
- TeXstudio: HEAD
- Qt: 5.15-rc
- OS: linux
- TeX distribution: N/A

### Actual behavior
```
In file included from src/texstudio.h:38,
                 from src/main.cpp:21:
src/pdfviewer/PDFDocument.h:312:15: error: field ‘highlightPath’ has incomplete type ‘QPainterPath’
  312 |  QPainterPath highlightPath;
      |               ^~~~~~~~~~~~~
In file included from ../../../Qt/5.15.0/gcc_64/include/QtGui/qbrush.h:49,
                 from ../../../Qt/5.15.0/gcc_64/include/QtGui/qpalette.h:46,
                 from ../../../Qt/5.15.0/gcc_64/include/QtWidgets/qwidget.h:48,
                 from ../../../Qt/5.15.0/gcc_64/include/QtWidgets/qabstractspinbox.h:44,
                 from ../../../Qt/5.15.0/gcc_64/include/QtWidgets/qstyleoption.h:47,
                 from ../../../Qt/5.15.0/gcc_64/include/QtWidgets/qabstractitemdelegate.h:45,
                 from ../../../Qt/5.15.0/gcc_64/include/QtWidgets/QAbstractItemDelegate:1,
                 from src/mostQtHeaders.h:14,
                 from src/main.cpp:14:
../../../Qt/5.15.0/gcc_64/include/QtGui/qmatrix.h:54:7: note: forward declaration of ‘class QPainterPath’
   54 | class QPainterPath;
      |       ^~~~~~~~~~~~
```

**Comment by sunderme** [comment]
I have tweaked it, so it compiles.
Still not sure ...

**Comment by MeanSquaredError** [comment]
I looked at the latest fixes and they look good to me. Haven't tested them, though, because Fedora still uses Qt 5.13.x).

 I am currently experimenting a lot with `PDFDocument` and related classes trying to fix https://github.com/texstudio-org/texstudio/issues/1069 and it seems to me that the code there is (sort of) old and has a bunch of minor glitches (especially in the part where it does the zooming). But it works :-)

**Comment by jonasstein** [comment]
Fixed in https://github.com/texstudio-org/texstudio/commit/0646ef03ffaec7edb39acd0563a53e0b7825c547
